### ISSUE TITLE
LMAO

### ISSUE THREAD

**Issue by DrAGoniPenguin** [YoungGarbage/Kawaii-TokenLogger#1]
Dude. 
Do you like punch your enter/return key when coding or something lol
My ocd
good stuff though

**Comment by YoungGarbage** [comment]
I've just looked at the code again, and yes, I was spamming the enter button very much, it also made me angry. Let me fix this shit

**Comment by YoungGarbage** [comment]
Lmao I just remembered about this, gotchu
